In [6]:
import numpy as np

In [7]:
lst = [1,2,3,4,5]
arr = np.array([1,2,3,4,5])

print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [8]:
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 73, 90, 92])

test_3_fixed = test_3 + 2
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

geremy_test_2 = test_2[3]
print(geremy_test_2)

manual_adwoa_test_1 = np.array([test_1[1], test_1[2]])

student_scores = np.array([test_1,test_2,test_3])

print(student_scores[2,0])

print(student_scores[:,-1])

[89 87 75 92 94]
[258 279 247 274 270]
[86.         93.         82.33333333 91.33333333 90.        ]
93
87
[87 91 92]


In [9]:
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
mask = a > 5
print(mask)

selected = a[a > 5]
print(selected)

selected = a[(a > 6) | (a < 4)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]


In [12]:
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

cold = porridge[porridge < 60]
hot = porridge[porridge > 80]
just_right = porridge[(porridge > 60) & (porridge < 80) ]

print(just_right)

[79 65 63 79]
